name: PHPStan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4' # You can choose the PHP version you want to use

    - name: Install dependencies
      run: composer install

    - name: Run PHPStan
      run: vendor/bin/phpstan analyze --level max
